version: '3.8'
services:
  bot:
    build: .
    command: python bot/bot_main.py
    environment:
      - DATABASE_URL=sqlite+aiosqlite:///./tg_gifts.db
    volumes:
      - ./sessions:/app/sessions
      - ./logs:/app/logs
      - ./tg_gifts.db:/app/tg_gifts.db
  buyer:
    build: .
    command: python buyer/api_server.py
    ports:
      - "8001:8001"
    environment:
      - DATABASE_URL=sqlite+aiosqlite:///./tg_gifts.db
    volumes:
      - ./sessions:/app/sessions
      - ./logs:/app/logs
      - ./tg_gifts.db:/app/tg_gifts.db
